### ISSUE TITLE
Why did you create a new analyzer?

### ISSUE THREAD

**Issue by sebastienros** [Codinlab/Lucene.FrenchAnalyser#1]
Isn't this one working for you?
https://lucenenet.apache.org/docs/3.0.3/d6/d26/class_lucene_1_1_net_1_1_analysis_1_1_fr_1_1_french_analyzer.html

**Comment by TFleury** [comment]
I started using it a while ago (before creating this module) and I encountered some problems... If I remember correctly, it was accent, apostrophe and conjugation sensitive.

I use my custom analyser on a site with thousands of content items and it produces better results.
